### ISSUE TITLE
Add colored leaf as icon to the leaf detail panel 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#101]

**Comment by gissoo** [comment]
@rlskoeser @jhimpele  [take a look at a few options I'm proposing](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1049%3A7940&t=jZghCJ9pcZuxVmSg-1), I'm struggling with alignment, your feedback to my question below might help me – I tried a few different leaf shapes and I like the thin one I'm showing most. 

I think from a ux perspective it makes most sense when the leaf is placed by the branch or on top of the panel rather than placing it by the title. If you think otherwise please justify it to help me.

**Comment by rlskoeser** [comment]
@gissoo I like putting the leaf with the branch label best — both semantically (connection to other leaves in the same branch) and for best use of vertical space.  I like it best with the smaller leaf on the left (second option in your third column), but I don't feel strongly about left or right.

**Comment by jhimpele** [comment]
Left of branch title.

**Comment by gissoo** [comment]
@rlskoeser @jhimpele thanks for your responses. 
- We discussed in person and all agreed on using the version with the narrower leaf placed on the left of the branch label. 
- [This is what the mobile version would look like ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1085%3A2081&t=grrfKlJsCLU1VgPf-1)– on desktop the leaf width is 20px and on mobile I've made it 14px, because it was too large. 

what do you think?

**Comment by rlskoeser** [comment]
Looks great!
