### ISSUE TITLE
As a user I'd like to select the plaque on the trunk of the tree to learn about the data on "dedication"

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#106]
what's in scope: 
- the logic of the interaction between the plaque and the panel
- the content/fields inside of the panel
- the visual styles of the plaque states

**Comment by gissoo** [comment]
@jhimpele @rlskoeser 
[The logic of the interaction here is the same as a leaf](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1038%3A3275&t=kHoIUsn1gDGbkDO8-1) (note and questions below): 
- Once the plaque is selected the panel would expand
- does this data point have any tags?
- do we want to specify "Trunk" where we normally see "Branch" inside the panel? 
- do we want to display a year for the panel and by the trunk? 
- @jhimpele currently I've placed the longer label you'd given me inside the panel as text – is this the right place for it, or will it be the title inside the panel? 

- I propose a visual style for the hovered and selected plaque where the plaque is crooked by default but on hover and select it becomes straight with a black outline. What do you think? I'd like the visual style to be a bit different from the leaves because a glow doesn't visually work here with a brown plaque. I'm open to suggestions

**Comment by jhimpele** [comment]
@gissoo @rlskoeser 
Responses:

- what does "expand" mean? The panel displays the dedication text?
- we could add tags, but not necessary.
- Can we leave the Trunk or Branch label blank, so neither appears?
- No year needed
- Sorry, can you send the longer label you have as text so we can edit it into a title for the panel?
- I like this interaction when hover/select. Though I'd go with dark brown instead of black for the outline, to match the same coloring on selected leafs that have a darker color. Or, could there be a small glow like the leaves?

**Comment by rlskoeser** [comment]
@gissoo I think the details for the dedication should be simpler — no "trunk" label, no tags, no year. Just a title, brief paragraph text, and photo. It's different from the leaves, and it stands alone, so it doesn't make sense to me to use the structures/metadata we have for the other items.

The crooked panel looks a little strange to me; maybe if you make the nail a little more obvious it would work better. Why would it straighten out on hover? (It doesn't seem logical for a sign on a tree to turn like that.)

**Comment by gissoo** [comment]
@rlskoeser @jhimpele please take a look here – your comments are very helpful, thank you – [I've revised the behavior on select and the the panel details](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1038%3A3275&t=laysiTUTL0Dz0Ytr-1) so that it looks like the project description panel in format

**Comment by jhimpele** [comment]
I'm not sure if I am seeing the Dedication panel.

I think the Panel title could just be "This work is dedicated to Karen Dolson Mosko (1968-2022)"

Then a subheading on a new line (in the body) below her name:
"Lunaape Language Teacher, Munsee Delaware Nation"

Then in the body (description):  
"I am blessed to be led by my ancestors to teach our language. This is a path that I will walk for the rest of my life."
- Karen Mosko

Read Karen Mosko'obituary [https://elliottmadill.com/tribute/details/816/Karen-Mosko/obituary.html#content-start]

**Comment by rlskoeser** [comment]
@gissoo the panel and interaction looks good to me.

I think you have the string for the plaque upside down, I imagined something more like this:
```
   o
  / \
 /   \
-------
|      |
-------
```

**Comment by gissoo** [comment]
@jhimpele @rlskoeser Since it looks like we are agreeing to [revise the background color of this page I was able to try the glow as well](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1101%3A5318&t=laysiTUTL0Dz0Ytr-1) – it wouldn't work on the lighter color.

**Comment by rlskoeser** [comment]
@gissoo I like the glow!

**Comment by gissoo** [comment]
ah thanks for illustrating, @rlskoeser :D – let me try it quickly. I don't really like putting a nail on the trunk for a plaque, I don't find it necessary, I've been looking at so many examples that don't involve a nail.

**Comment by jhimpele** [comment]
@gissoo I'm now seeing the space constraints on the dedication panel, and want to suggest this:

This work is dedicated to the memory of
Karen Dolson Mosko (1968-2022)

Lunaape Language Teacher, Munsee Delaware Nation

"I am blessed to be led by my ancestors to teach our language. This is a path that I will walk for the rest of my life."

Read Karen Mosko's obituary [https://elliottmadill.com/tribute/details/816/Karen-Mosko/obituary.html#content-start]

[Use what ever sizing makes visual sense]

**Comment by jhimpele** [comment]
Good point about the tree growing beyond the string, @rlskoeser. But since I now don't have really strong feelings I would defer to @gissoo. (Of the strings, I still prefer the second one.)

**Comment by rlskoeser** [comment]
@gissoo @jhimpele I don't feel strongly (unless implementation turns out to be difficult for some reason); let's move on with whatever you think is best.

**Comment by gissoo** [comment]
@rlskoeser @jhimpele for the scope of this issue I think I've revised the dedication panel and simplified it. I think we also like the glow that would work on the new darker page background color. I'll go ahead and close this issue.
