### ISSUE TITLE
cleanup an assortment small visual issues 

### ISSUE THREAD

**Issue by quadrismegistus** [Princeton-CDH/lenape-timetree#109]
- [x] ~Horizontal scroll activates on main page when it probably shouldn’t~
  - I actually can't recreate this anymore?
  - Actually I can, only when the detail window is closed, then all the sudden both scrollbars appear on the page even though not necessary
  - Now I can't again?
- [x] Horizontal scroll activates on the text info window due to a URL; should probably disable overflow
- [x] Horizontal and vertical scroll have the scrollbar space at right and bottom there even when not needed
- [x] Cursor doesn’t need to shift to the text cursor when hovering leads
- [x] ~Unicode error (curly quotes)~
  - This one also just disappeared and started rendering correctly!?
- [x] Escape closes detail panel

**Comment by rlskoeser** [comment]
sorry, just seeing your comments now — I think the links will probably be fixed via content editing.

The X hasn't been styled & positioned based on the designs; this is just a quick version I threw in so I could work on functionality. Implementation issue for that is #84 if you have any interest in taking it on.

Should we close this based on merging #116 ?

**Comment by rlskoeser** [comment]
going to close this as done, we can open new issues as needed
