### ISSUE TITLE
As a user,  I want the url to change when I select a tag so that I can bookmark or share the timetree with a specific tag selected.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/lenape-timetree#114]
## dev notes

Similar to how we update browser location with a hash for the selected leaf, we should add a parameter for the selected tag; should be able to use [searchParams](https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams) to parse and update params and generate a string to replace the location with. 

Want similar behavior to leaf hash — detect if there is a selected tag when the page loads and activate that tag. URL should use slugs but active tag display should be name; may need to generate a dict of tags and tag names somewhere, possibly in Hugo template as json for consumption by timetree code.

**Comment by quadrismegistus** [comment]
We don't want to use `[server]/tags/land-claims`, but `[server]?tag=land-claims` ?
