### ISSUE TITLE
As a content admin, I want leaves automatically positioned in the tree based on their branch and century, so that the display follows the agreed upon logic.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/lenape-timetree#12]
force-directed layout that takes branch and century into account (nodes don't yet fall exactly within their century band)

available for review on the current version of the site:
https://princeton-cdh.github.io/lenape-timetree/

please review and provide feedback about next steps / how to refine the layout

**Comment by gissoo** [comment]
@rlskoeser thank you so much! I think it would be helpful to 
1. see the nodes falling within their century band, 
2. and also if we can move the tree to the left as much as possible so we can see how much space there is left for the panel.
3. add labels to the leaves to see what it'll look like
