### ISSUE TITLE
determine other content and their placement on the footer 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#138]

**Comment by gissoo** [comment]
@rlskoeser @jhimpele [does this footer](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1414%3A6082&t=ZogyV80BN8jIbEv9-1) look ok to you and does it have the information you expected to see? 

a few questions and requests
- I'll need a VizE lab logo, where can we get that?
- It would be great if there is a NAISIP logo that's in white, the colored version is not the best for this background. Who should I contact?
- Do we have to use the NAISIP logotype? I mean this one below – it's not readable on our page background and it's also not easy to read it in that size – can we just use the logo (i.e. the visual without the text)?
<img width="414" alt="Screenshot 2023-04-11 at 4 55 08 PM" src="https://user-images.githubusercontent.com/44615389/231285946-35120b6f-44d7-4963-ba6c-b23811be07b2.png">
- do we need any version numbers? or cc by? or ISSN?

**Comment by rlskoeser** [comment]
@gissoo I haven't been thinking of version numbers, I'm not sure they make sense for this project. We will have "releases", but I haven't been thinking of it in terms of versioned functionality. Does that seem reasonable?  (Although I like the convention we've started of linking to the github repo from the version number...)

I don't think an ISSN is appropriate.

I just looked, and we didn't specify CC-BY in the charter; we should state rights somewhere explicitly. It would be nice to make the content CC-BY if @jhimpele is comfortable with that.

I think these look good.

**Comment by gissoo** [comment]
@jhimpele if you have a designer who is working on it please give me an SVG, that way size won't matter. who should I reach out to regarding the NAISIP one?

**Comment by jhimpele** [comment]
Great @rlskoeser 

@gissoo I will push to get our logo, if not a placeholder for you. As far as NAISIP goes, I'd check with Keely and Sarah Malone, I suppose.

**Comment by gissoo** [comment]
- thank you! @jhimpele I followed up about the NAISIP one with Keely, she will initiate an email with Sarah Malone and Sarah Rivett and will cc me too 
- thanks for uploading the VizE lab temp logo 

[Please check out the revised footer here ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1414%3A6082&t=2wD8jK3Yt38QnF64-1) – and [here on mobile ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1414%3A6189&t=2wD8jK3Yt38QnF64-1) 
- I've added the CC-BY-NC and 
- I've added the version number per Rebecca's advice on slack, and 
- placed the VizE lab temp logo – we may or may not need the SVG version, the file type is now SVG but its source is actually an image so it may or may not get pixelated for our use case. 
- I think we'll just use the CDH blue logo since the others are in color, we'll see what the final versions will look like.

**Comment by jhimpele** [comment]
@gissoo All looks good!

**Comment by gissoo** [comment]
@rlskoeser I'm not sure, I'm trying to systematize the footer in our projects and also use what I can from the design system project at OIT – the OIT template places accessibility and rights at the bottom. We did the same thing for PGP – can we justify why we should reorder the footer content for this project? I'd rather we do not make it different on mobile, it would be better to apply any changes on all sizes.

**Comment by rlskoeser** [comment]
@gissoo that's a good reason to keep them consistent; I'm convinced.

**Comment by gissoo** [comment]
@rlskoeser @jhimpele how do [the logos on desktop](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1493%3A1883&t=WefLntFwiLMoktfm-1) look to you? I resized them so they are a bit smaller so they could fit better on narrower desktop sizes 

and how about [on mobile](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1493%3A2095&t=WefLntFwiLMoktfm-1)? I think they need to be more readable on mobile, so don't want to make them smaller here.

**Comment by rlskoeser** [comment]
@gissoo I'm satisfied with these.

**Comment by jhimpele** [comment]
@gissoo they work for me too. You might want to check the readability of CDH....

**Comment by jhimpele** [comment]
@gissoo I will get that white logo for you soon.

**Comment by gissoo** [comment]
Thank you!  
Thanks, @jhimpele, I slightly increased the height of CDH and the VizE lab logos and decreased spacing by 6px on desktop. I'll go ahead and close this issue. Once you have the white logo I'll make a chore and add it to the designs

**Comment by gissoo** [comment]
@jhimpele great! please send it through email and I can look into the best export options

**Comment by jhimpele** [comment]
[A picture containing text, font, graphics, symbol  Description automatically generated]


Jeffrey Himpele.
Director, VizE Lab for Ethnographic Data Visualization
Lecturer in Anthropology
vizelab.princeton.edu<http://vizelab.princeton.edu/>


From: gissoo ***@***.***>
Date: Tuesday, April 18, 2023 at 1:12 PM
To: Princeton-CDH/lenape-timetree ***@***.***>
Cc: Jeffrey D. Himpele ***@***.***>, Mention ***@***.***>
Subject: Re: [Princeton-CDH/lenape-timetree] determine other content and their placement on the footer (Issue #138)

@jhimpele<https://github.com/jhimpele> great! please send it through email and I can look into the best export options

**Comment by jhimpele** [comment]
Just sent as psd.
Thanks,
Jeff.

Jeffrey Himpele.
Director, VizE Lab for Ethnographic Data Visualization
Lecturer in Anthropology
vizelab.princeton.edu<http://vizelab.princeton.edu/>


From: gissoo ***@***.***>
Date: Tuesday, April 18, 2023 at 1:12 PM
To: Princeton-CDH/lenape-timetree ***@***.***>
Cc: Jeffrey D. Himpele ***@***.***>, Mention ***@***.***>
Subject: Re: [Princeton-CDH/lenape-timetree] determine other content and their placement on the footer (Issue #138)

@jhimpele<https://github.com/jhimpele> great! please send it through email and I can look into the best export options
