### ISSUE TITLE
make the century numbers easier to read  

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#139]

**Comment by gissoo** [comment]
@rlskoeser what do you think about this? 
- [I like this better now! ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1304%3A990&t=16Yj0q6JutyqKogd-1) 
- [I tried what I imagined](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1297%3A1354&t=16Yj0q6JutyqKogd-1) but I don't like it as much, takes too much real estate.

**Comment by jhimpele** [comment]
Hmm. I actually like the one you imagined better. Even though it takes of more visual space, it seems less disruptive or choppy than individual boxes. In other words, it blends in better.

**Comment by rlskoeser** [comment]
The second option is pretty boxy, but I also don't like losing so much space to the century column. 

Are we concerned with century numbers overlapping with leaves, or just visibility/readability in general?

Could we give them a partial opacity background that matches the tree background so it's only visible if there is overlap with leaves?

I do have an issue in the backlog to adjust the leaves so they don't overlap with the century numbers (as much / at all), and the way I'm handling zoom right now wouldn't change whether they overlap or not.

**Comment by gissoo** [comment]
@rlskoeser the concern is the readability 

OMG! YES! That's it! @rlskoeser @jhimpele [I love this so much better, please take a look] (https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1355%3A2985&t=iaSL01uLrmEeK9OM-1), thank you, Rebecca :brain: :eyes: !!!

**Comment by jhimpele** [comment]
That works because it makes the shading is not needed...

**Comment by rlskoeser** [comment]
that looks good to me!

**Comment by gissoo** [comment]
Thanks!! I'll go ahead and close. I've documented specs on padding in the figma file.
