### ISSUE TITLE
Search for and propose two typefaces that are appropriate for the site's topic and concept

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#14]

**Comment by gissoo** [comment]
@rlskoeser @jhimpele Apologies for the delay – I've expanded my search and am proposing a larger pool of typefaces. For this stage I've structured them so that you see each as a title and body text following Rebecca's comments to make it easier to compare them against each other. [Here they are on a light and dark background fwiw](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=278%3A152&t=zpqRGJbwtRack98d-1). Please let me know which ones if any you like a lot, and which ones you absolutely dislike.  

Note: 
- There are two fonts that are only displayed as titles because they only come in bold weights so we won't be able to use them for body text. 
- I've labeled them by numbers and letters (like a matrix diagram) so you can refer to them that way e.g. "1a".

**Comment by jhimpele** [comment]
@gissoo @rlskoeser 
Choices for fonts. Is there a way we could preview some combinations? Either here or in person on Monday? 

Title fonts serif: 1b , 1e , 2a , 3c , 4a
Title fonts sans serif: 2e , 2f , 3f

Body fonts serif: 1d , 3c
Body fonts sans serif: 1f , 2d , 3f , 4c , 4f

**Comment by gissoo** [comment]
This issue has been reviewed and the team seems to be liking "overlock" and "ubuntu". 
However we'd still want to review more "display" fonts for the site header. 
![Screen Shot 2023-01-04 at 5 29 50 PM](https://user-images.githubusercontent.com/44615389/210662235-94ee3aa3-2bf4-4e54-80c5-ee49f9b41f1a.png)
