### ISSUE TITLE
resolve jumping tree on safari 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#140]
on safari there is a jump in the position of the tree, when some leaves are active the tree sits higher and with other it sits lower. (e.g. on #exodus it sits higher then on #midwest-resettlement it goes down a lot)

_Originally posted by @gissoo in https://github.com/Princeton-CDH/lenape-timetree/issues/130#issuecomment-1496048872_
            
According to Rebecca: max height is not working on safari either.

**Comment by rlskoeser** [comment]
fix for this also included in #141
