### ISSUE TITLE
add tagline to the header under the site title 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#146]
this is the new text: Interweaving histories of Lunaapahkiing, “the land of the Delaware Lenape” and the unceded lands of the Princeton University campus.

**Comment by gissoo** [comment]
@rlskoeser @jhimpele what do you think about [the line added below the site title? ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1414%3A5886&t=ZogyV80BN8jIbEv9-1) - please look at both desktop and mobile. 

- @rlskoeser I have created an autolayout contianer and put everything in the header inside it, so all the new vertical spacing and old padding are documented in there.  
- the font is in italics, and is 18px on desktop and 16 on mobile.

**Comment by rlskoeser** [comment]
@gissoo it looks really long... Are we proposing that this will always display? Can you show how it looks with the timetree on the homepage?

Could we put it on one line on desktop by any chance?

Could you try my idea of omitting it from the header on mobile and including it at the top of the intro?

**Comment by rlskoeser** [comment]
@jhimpele let's put the tagline in the google doc where you have been drafting the homepage text so we can wordsmith it there and brainstorm other ways to phrase it.

@gissoo could you suggest a target length?

**Comment by rlskoeser** [comment]
I like that option better on mobile! 

Is it weird that we're repeating the project title in the intro? (IDK why I'm only noticing it now; maybe it bothers me because your version in Figma is using a different title.)

**Comment by jhimpele** [comment]
I've copied the current version on the HOME doc for editing. YES< we should remove the same line from the Intro panel if it repeats....

https://docs.google.com/document/d/1SzALkoCaS-6nGTrBIJBg7ypP9h4iPEChQc6Y5zm9q9g/edit

**Comment by gissoo** [comment]
According to our conversations we have made the following decisions:
- we are going to place the tagline inside the panel as shown [here on mobile](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1502%3A4315&t=WefLntFwiLMoktfm-1) and [here on desktop](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1502%3A4210&t=WefLntFwiLMoktfm-1)
- we are keeping the header within the intro panel, and write welcome in the Lenape language per Keely's proposal.
