### ISSUE TITLE
Make a favicon

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#148]

**Comment by gissoo** [comment]
@rlskoeser @jhimpele I have created a favicon for the site. The favicon is what you see here in your tab on the browser like the below – so when someone is viewing the lenape site they will see a visual that represents the project. This is super small so it needs to be readable.
<img width="223" alt="Screenshot 2023-04-11 at 4 50 11 PM" src="https://user-images.githubusercontent.com/44615389/231285008-f07bf894-a0e6-41ed-9950-8780e149c8f9.png">

I am proposing two versions, do you like any of these two proposals? [Here is v1 ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1414%3A9191&t=ZogyV80BN8jIbEv9-1)and [here is v2](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1414%3A9141&t=ZogyV80BN8jIbEv9-1)

**Comment by rlskoeser** [comment]
Thanks for working on this, Gissoo. I like v1.

**Comment by jhimpele** [comment]
Same for me: v1 
What do @rlskoeser and @gissoo think of using the orange leaf color to hint at the Princeton U origins of the site?

**Comment by rlskoeser** [comment]
Orange for Princeton could work, but I wonder if there is enough contrast at small scale.  @gissoo what do you think? 

Otherwise I like using light green color we used for resistance & resurgence (that's the one you're using now, right?).

**Comment by rlskoeser** [comment]
@gissoo I wondered about the contrast when I looked at the favicon!  Could you show us the revised color in context with the other leaves?

**Comment by jhimpele** [comment]
It's possible that the orange favicon could seem university-centric, but we did adopt that reason for making the university the center and orange branch of the tree.....I don't have strong feelings about the favicon color....

**Comment by gissoo** [comment]
@jhimpele do you have any thoughts on the revised orange color per my earlier comment above?

**Comment by gissoo** [comment]
I'm fine with using the orange leaf for our favicon too, I agree with you, I checked with Keely too and she is fine too.

**Comment by jhimpele** [comment]
Excellent!

**Comment by jhimpele** [comment]
Thanks for checking with Keely. All looks good.  It's hard to tell, but the orange in the legend still looks darker....At any rate this new color works. Thanks for all the fast progress this week.

**Comment by rlskoeser** [comment]
@gissoo if the orange is not enough contrast then I think we should switch; we'll need all the variant colors for the new orange (if they should change), but it's easy enough to update the color variables in the stylesheets. I like both of them and don't feel strongly about it visually.

I don't have a preference for the color for the favicon; orange is fine with me.

**Comment by gissoo** [comment]
@jhimpele thank you for flagging! I updated the new orange color on the legend as well. 
@rlskoeser thank you for flagging! To my surprise we don't have to change any of the colors for the orange leaf states :D – the new orange sits beautifully with the rest of our colors, it's looking better than the previous orange, I should have used this color from the beginning! Here is the [updated colors for dev table
](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=996%3A1639&t=WefLntFwiLMoktfm-1) – #D89479 – I have not rearranged the branch colors to match our agreed branch order on the tree, does this matter to you? I can change it if needed.

**Comment by rlskoeser** [comment]
@gissoo that's great about the colors. Do you want to make the change? Here's the relevant part of the file on the develop branch: https://github.com/Princeton-CDH/lenape-timetree/blob/develop/themes/timetree/assets/scss/base/_colors.scss#L16-L30 

(If it doesn't make sense to you or doesn't look easy, I can handle it easily enough - it looks like there may be some redundancy I can clean up anyway).

Please don't rearrange the branch colors. I've already mapped the a-e sets of colors to the named branches in the order we decided on, so rearranging them now would be confusing and cause more work.

**Comment by gissoo** [comment]
@rlskoeser Thank you! I have generated the favicon files, detailed information regarding the location of the files and the code are in implementation issue #152 that I just created. 

I'll go ahead and close this issue
