### ISSUE TITLE
Propose type sizes for each content type on desktop and mobile

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#15]
not in scope: the site title / display font

**Comment by gissoo** [comment]
@rlskoeser @jhimpele 
- please take a look at the type sizes I've proposed for desktop and mobile [here on Figma ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=403%3A669&t=DJCP8S666b3lau1W-1) and let me know what you think  
- You can look at them on the desktop and mobile layouts or the typography table I've created. 
- I've included some of the leaf titles on desktop as a way to test. 
 
I'm moving forward with Overlock as it was more promising than Ubuntu as far as its base scale and kerning. 

Note: the site title/display font is out of scope for this issue, I'll address it in another issue soon.

**Comment by jhimpele** [comment]
Looks good. I have a few related points, perhaps for next week: the tradition and events "rows" or bands can be removed. Should we keep the branch names as placed above them? And there will only be one item on the trunk (the plaque). And let's continue our discussion of how to make the trunk appear as a single trunk...shading? Otherwise, I think we are looking good with Overlock!

**Comment by rlskoeser** [comment]
@gissoo the sizes all look good to me; everything seems very readable and I like how the Overlock is working out; glad it was a good solution for the sizing.

In the table of font sizes and styles, under navigation, you have "mobile: footer default" repeated, I think the second one should be selected (it looks like you forgot to change the name, I can tell from the styles).

You list buttons and tags in the nav section, do they use the same type styles as footer default?

It looks like these are ready to implement, would you create an implementation issue when you close this design issue?

**Comment by gissoo** [comment]
@jhimpele thank you for writing. I have removed the traditions and events and left one circle as an indicator for the plaque in the trunk. The revised tree style will be in a separate issue. About the placement of the leaf labels I'm not sure, having a difficult time seeing them all placed the same way, it would be helpful to test that in implementation because the spacing within the visualization displayed in Figma won't be matching the implementation.

**Comment by gissoo** [comment]
@rlskoeser thanks for writing! I have fixed the table, yes, they will use the same type styles and footer default, I've fixed the label so it says tags and footer. But we don't have text "buttons". I'll eliminate that
