### ISSUE TITLE
As a user, I want to see a legend for the branches in the intro panel so that I can understand the content is organized by themes and recognize the meaning of the leaf colors.

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#155]
[here are the designs](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1355%3A2706&t=VhV5CRGDNIEnueWJ-1) for desktop and mobile 

Note: the legend is inside an auto layout structure, within the panel's auto layout structure – you can inspect them to see specs on spacing and padding

**Comment by rlskoeser** [comment]
completed in #170
