### ISSUE TITLE
adjust the green leaves so it would be easier to distinguish them from each other 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#156]

**Comment by gissoo** [comment]
@jhimpele @rlskoeser [I've slightly revised both greens](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1541%3A2227&t=VhV5CRGDNIEnueWJ-1), the change in the R+R green is more apparent. Let me know what you think

**Comment by jhimpele** [comment]
That difference is more detectible now. Great job!

**Comment by rlskoeser** [comment]
Yes, agreed - this is better.

**Comment by gissoo** [comment]
thanks! I have made the change in the code to both greens. I'll go ahead and close.
