### ISSUE TITLE
Add VizE lab white logo to the footer on figma 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#159]
@jhimpele @rlskoeser  I've added the white VizE lab logo to [the footer on mobile and desktop](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1493%3A2095&t=VhV5CRGDNIEnueWJ-1). How does this look to you? It's so much better now!

**Comment by jhimpele** [comment]
Looks a LOT better. Great idea. I will revise the VizE one to add a little more space above and below the VizE Lab text, but we can use this one for now.....THANKS.

**Comment by rlskoeser** [comment]
@gissoo loks good!

**Comment by gissoo** [comment]
thanks! I have placed the logo file in the logos folder, I'll go ahead and close
