### ISSUE TITLE
revise the site title in the site header 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#168]

**Comment by rlskoeser** [comment]
@gissoo fonts and spacing look fine to me. I like the italics for the tagline. 

If the tagline is in Overlock then it won't need to be an image, which is nice.

I'd rather not give that much space to the header on mobile, is putting the tagline in the beginning of the intro panel still an option?

**Comment by jhimpele** [comment]
This is _really_ nice to see, @gissoo. I do think the font size on the tagline could be a little larger, without causing it to fall on three lines in mobile. Can we see it a little larger? Thanks!

**Comment by gissoo** [comment]
thank you for your comments –

@jhimpele I'm hesitant about increasing the size:
- even though the number of lines wouldn't increase on mobile there are two factors that increase the overall height of the header container by 6px. 
- based on my bit of research it would be better if the tagline in the header is smaller than our H1 sizes. 

[I don't like this new revision](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1668%3A5093&t=DJkvYZGXoVgtDe5n-1)

@jhimpele following on Rebecca's question: do we want to consider putting the tagline inside the intro panel at all on mobile?

**Comment by jhimpele** [comment]
hi @gissoo I do like the larger font on the desktop. It doesn't look diminished, nor too big. It's hard to judge the mobile since it's not constrained by the screen. But if you think the tag line works better in the panel, that's fine. Wouldn't it nevertheless take up the same vertical space?

**Comment by rlskoeser** [comment]
Putting the tagline in the panel takes up the same vertical space when the page loads, but it's space we get back once we collapse the intro or open a leaf.

**Comment by jhimpele** [comment]
That’s a great idea!


Jeffrey Himpele.
Director, VizE Lab for Ethnographic Data Visualization
Lecturer in Anthropology

vizelab.princeton.edu<http://vizelab.princeton.edu/>


On 4/27/23, 9:16 AM, "Rebecca Sutton Koeser" wrote:


Putting the tagline in the panel takes up the same vertical space when the page loads, but it's space we get back once we collapse the intro or open a leaf.

**Comment by gissoo** [comment]
@rlskoeser @jhimpele here are the changes I've made on [desktop](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1793%3A2304&t=UPpb4awa51quxLxp-1) and [mobile](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1793%3A2432&t=UPpb4awa51quxLxp-1) – please let me know what you think: 
1. the title on desktop and mobile have changed to "Lunaapahkiing Princeton Timetree"
2. the subtitle is on the header on desktop and inside the panel on mobile 
3. I've added the temporary welcome text as the panel's header on desktop and mobile
4. on mobile the welcome text is above the subtitle, and the subtitle is placed more closely to the description 
5. After our meeting I thought of proposing this: we make the "Princeton Timetree" smaller only on mobile so that it wouldn't take so much space on the header

**Comment by jhimpele** [comment]
@gissoo and @rlskoeser Great work. The only thing that I'm still not sure of is having the subtitle in the mobile intro panel. It's a little confusing to me. Also, on both desktop and mobile, are we going to have an English translation in parens and smaller font? An * with translation at bottom?

**Comment by gissoo** [comment]
@jhimpele regarding translation for the welcome text Keely mentioned that to me yesterday when she reviewed the designs. [I would suggest something like this ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1793%3A2304&t=vPBAuQVyxwf8m2JN-1) – what do you think?

**Comment by jhimpele** [comment]
It works fine! Thanks.


Jeffrey Himpele.
Director, VizE Lab for Ethnographic Data Visualization
Lecturer in Anthropology
319-320 Burr Hall | Princeton University

vizelab.princeton.edu<http://vizelab.princeton.edu/>


On 5/10/23, 1:23 PM, "gissoo" wrote:


@jhimpele<https://github.com/jhimpele> I like the way it looks, and I'm also refraining from creating a new type style just for that, let me know if you think it needs to have a different style

**Comment by gissoo** [comment]
@rlskoeser @jhimpele thank you both for reviewing. Based on your comments I have reviewed the designs, below are the specific updates:

[on mobile](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1793%3A2432&t=epwVFkcOmF4rJzh8-1):
1. the site title and subtitle are both in the site header
2. the "PRINCETON TIMETREE" portion of the header is a bit smaller to help save some vertical space
3. I've reduced the line height between "LUNAAPAHKIING" and "PRINCETON TIMETREE" to help save vertical spacing 
4. The new welcome text has been added, revised it so that it's bold italics now, and the translation fits on the same line with an 8px horizontal spacing (thanks for suggesting that, Rebecca!) 

[On desktop](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1793%3A2304&t=epwVFkcOmF4rJzh8-1):
1. everything in the header is the same as before 
2. the new welcome text and translation are added and are placed on the same line, again with an 8px horizontal spacing

Please let me know if you're okay with these revisions so I can place the new titles as svgs on github.

**Comment by jhimpele** [comment]
Great job @gissoo!  I like! We add the credit to Kristen Jacobs through GitHub?

**Comment by rlskoeser** [comment]
Wonderful! I think we're ready to run with these versions.

@jhimpele yes, all the text for the intro panel will be in a content document in github, so we can handle the credit that way. I can set it up when I implement the revised title and add the welcome.

**Comment by jhimpele** [comment]
Excellent! Thanks.


From: Rebecca Sutton Koeser ***@***.***>
Date: Monday, May 15, 2023 at 4:53 PM
To: Princeton-CDH/lenape-timetree ***@***.***>
Cc: Jeffrey D. Himpele ***@***.***>, Mention ***@***.***>
Subject: Re: [Princeton-CDH/lenape-timetree] revise the site title in the site header (Issue #168)

Wonderful! I think we're ready to run with these versions.

@jhimpele<https://github.com/jhimpele> yes, all the text for the intro panel will be in a content document in github, so we can handle the credit that way. I can set it up when I implement the revised title and add the welcome.

**Comment by gissoo** [comment]
thank you both for your reviews!! I have uploaded the site title svgs to github! I'll go ahead and close this issue.
