### ISSUE TITLE
Propose color palettes for the visualization that can work together while following accessibility requirements  

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#17]

**Comment by gissoo** [comment]
@rlskoeser @jhimpele 
- I've organized the color options by numbers and put them into two separate groups: one where only the branches are colored and one where areas around the branches are colored instead. 
- You can see the palette used for each version right above each page. 
- I think group "Colored Branches" may be easier to work with for accessibility therefore I explored it more. 

[Here they are on Figma.](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=238%3A3630&t=zpqRGJbwtRack98d-1) – Let me know your thoughts and if there are any versions you like or absolutely dislike.

**Comment by jhimpele** [comment]
Nice choices @gissoo , I'm leaning toward 1, 5, and 6. 5 is leading for me, since if gives a couple bright colors that can stand out from the palette.

**Comment by gissoo** [comment]
This issue has been reviewed and the team seems to agree on color palette no. 5. 
![Screen Shot 2023-01-04 at 5 27 01 PM](https://user-images.githubusercontent.com/44615389/210661886-759b1d54-5599-40e0-aab5-76d99430ef40.png)
