### ISSUE TITLE
Simplify the leaf paths 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#174]

**Comment by gissoo** [comment]
@rlskoeser [is this simplified enough](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1631%3A4582&t=KpCAbb2QDwvChu9z-1)? Or you were thinking even fewer paths than 7?

**Comment by rlskoeser** [comment]
@gissoo IDK, let's try it! Is there a way to see the path in the svg in Figma, or do I need to export it as svg to see that?

**Comment by gissoo** [comment]
@rlskoeser to see the path's code we'll need to export it as svg, but to see the paths (visually) you can inspect it on figma and I can show you also.

**Comment by gissoo** [comment]
@rlskoeser here is the path for the leaf I revised yesterday. 

```
<path d="M69.7236 60.1112C68.3131 55.4393 64.6687 48.6826 64.6687 48.6826C64.6687 48.6826 64.8945 46.3792 51.7016 49.9987C38.5088 53.6182 31.1595 81.5769 31.0423 84.0672C30.9251 86.5576 30.4659 98.3516 34.2382 106.249C38.4116 114.985 51.7016 123.847 51.7016 123.847C51.7016 123.847 69.7236 100.124 71.0423 84.0672C72.361 68.0107 72.4317 69.0809 69.7236 60.1112Z" fill="#ADCF9F"/>
```

**Comment by gissoo** [comment]
@rlskoeser here is the flipped version of the same leaf 
```
<path d="M2.72225 63.7363C4.13279 68.4082 7.7772 75.1648 7.7772 75.1648C7.7772 75.1648 7.55138 77.4682 20.7442 73.8488C33.9371 70.2293 41.2864 42.2706 41.4036 39.7802C41.5208 37.2898 41.98 25.4959 38.2076 17.5988C34.0343 8.86215 20.7442 5.81625e-06 20.7442 5.81625e-06C20.7442 5.81625e-06 2.72225 23.7237 1.40357 39.7802C0.0848902 55.8368 0.0141391 54.7666 2.72225 63.7363Z" fill="#ADCF9F"/>
```

**Comment by gissoo** [comment]
@rlskoeser following our conversation, [I've picked the five leaf variants that I think could work ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1653%3A4688&t=DJkvYZGXoVgtDe5n-1)– I've placed them in individual frames ready to be exported as separate svgs, and also all in one frame, in case you'd like to export them or just view them next to each other on Figma

**Comment by rlskoeser** [comment]
I think this is enough for me to work from when I'm able to get back to it. Let's go ahead and close this issue.
