### ISSUE TITLE
Export svg of tree to be used for JS error design, social media preview image, and website banner/card

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#175]

**Comment by rlskoeser** [comment]
I've generated a couple of exports using svg crowbar browser bookmarklet, and it seems to be working well. I uploaded one version to Figma, and was able to turn off the label layer visibility. I added a recent version to the noscript branch (#206).  I manually removed the labels svg group from the dom before exporting. I can easily generate another version when we want to update, if we make changes to the tree that are affecting the visuals.

Figma seems to pick up on id attributes, so it may be helpful to use those more consistently, right now I'm using classes for some of the groups. - probably depends how much we're doing with it in Figma if this matters, but not a very difficult change for me to make if it helps.
