### ISSUE TITLE
Design buttons to zoom in and out of the tree on desktop and mobile 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#176]

**Comment by gissoo** [comment]
@rlskoeser @jhimpele what do you think of the zoom in and out button on [desktop](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1811%3A3159&t=UPpb4awa51quxLxp-1) and [mobile](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1811%3A3830&t=UPpb4awa51quxLxp-1)? 

- - I would propose the following interactions:
- when zooming in and out of the tree the zoom's position would be centered on the tree 
- when zooming out of a specific leaf the tree again becomes centered 
I am imagining this interaction will have to work with selecting the buttons and dragging using the mouse. I have to dig in more to see if there are other options for accessibility. 

- - do we want to keep the "reset to zoom" button? Or is it obsolete? I think it would be nice to keep it but wasn't sure how much it would serve our users considering the extra space it will take.

**Comment by rlskoeser** [comment]
Buttons look fine to me, Gissoo. 

I think we should keep the reset. Should it be hidden or just disabled when the tree is at full zoom?

Can we start with what is easy to implement for zoom? (I think default behavior is close to what you propose)

**Comment by gissoo** [comment]
Thanks, @jhimpele and @rlskoeser !!  – Please let me know what you think: 

- @jhimpele I was thinking to look into moving the tree around after the zoom, i.e. the dragging part ...based on my research we will need a way to move around the tree using the keyboard so that we wouldn't depend on using the mouse, such as the up, left, right, and down arrows to move around the tree, not sure. 
- Thank you, both. I also think we should keep the reset. On mobile I don't think we should display the reset when it's at full zoom because of space, in this context displaying it does not serve any  cognitive purpose either. But on desktop it may make more sense to display it. 
- @rlskoeser sure, I agree on implementing what is easy with zoom. 
- Yes, I think the +/- would need to be visible but disabled when invalid, I've applied these here based on [default view](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1878%3A3628&t=epwVFkcOmF4rJzh8-1) vs. [selected leaf](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1878%3A3295&t=epwVFkcOmF4rJzh8-1)/[interaction with zoom](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1811%3A3159&t=epwVFkcOmF4rJzh8-1)

**Comment by rlskoeser** [comment]
@gissoo this all looks great to me.

**Comment by jhimpele** [comment]
I concur with Rebecca.
Thanks, Gissoo.


On 5/15/23, 5:15 PM, "Rebecca Sutton Koeser" wrote:


@gissoo<https://github.com/gissoo> this all looks great to me.

**Comment by gissoo** [comment]
thank you, both! 
@rlskoeser I forgot to mention one thing here, for the disabled state of the +/- buttons is basically the actual + or - in 40% opacity. I did not touch the brown square container they sit on because we want the container to be 100% opaque at all times in the case that they overlap with the tree.
