### ISSUE TITLE
setup percy visual review workflow

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/lenape-timetree#18]
Adapt from geniza; start with homepage (should eventually have one content page also). At least mobile + desktop; maybe a tablet size also.

**Comment by gissoo** [comment]
@rlskoeser thank you! Can we do 320px and 1440px for screen sizes? I was doing some research yesterday and found out it's still better to design in 1440 than 1280, I'll revise my figma mockups as well.

**Comment by rlskoeser** [comment]
@gissoo sure! Let me figure out where to configure that, I'll revise and let you know

**Comment by gissoo** [comment]
The other thing I'm noticing is how on the Percy screenshots the upper leaves, the trunk and some lower leaves are cut off.

**Comment by rlskoeser** [comment]
> @rlskoeser The other thing I'm noticing is how on the Percy screenshots the upper leaves, the trunk and some lower leaves are cut off.

yes, there are still some display issues — I'm planning to handle them under a separate task; maybe it makes sense to do as part of the headers & footers? I want to get your input on how to size the viz container.

Here's the [new build for this branch with the sizes you requested](https://percy.io/3201ecb4/lenape-timetree/builds/23472871/changed/1311855043?browser=edge&browser_ids=18%2C30%2C31%2C32&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1440&widths=330%2C1440)

**Comment by rlskoeser** [comment]
wow, sorry! I thought I copied your sizes exactly, IDK how I messed that up. Thanks for catching.

Here's [the latest build](https://percy.io/3201ecb4/lenape-timetree/builds/23473301/changed/1311895271?browser=edge&browser_ids=18%2C30%2C31%2C32&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1440&widths=320%2C1440), I just confirmed that it's 320 now instead of 330.

**Comment by gissoo** [comment]
thank you!!
