### ISSUE TITLE
misc ui/visual cleanup and updates

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#190]
h1 size:
> You and Jeff had asked that we make the H1 on mobile larger. I've revised the H1 so that it's 26px with line height of 39px on desktop and 24px with line height of 36p on mobile. It would look [like this on desktop](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1793%3A2304&t=vPBAuQVyxwf8m2JN-1) and [this on mobile ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1793%3A2432&t=vPBAuQVyxwf8m2JN-1)

- [x] update h1 size
- [x] remove hover effect on century numbers
- [x] update figure caption sizes
- [x] update footer logos
- [x] update site title image and tagline
- [x] add welcome text to the intro
- [x] move audio caption above audio; check spacing for audio figure; add margins to audio figcaption

**Comment by rlskoeser** [comment]
@gissoo the figma links in this issue no longer work and I'm having trouble finding the typography page in figma. The mobile size you provided in the issue notes is the size I already had, so I wanted to check. Please let me know where I should be looking!

**Comment by gissoo** [comment]
@rlskoeser The figma links are working for me! I can take screenshots of it for you, sorry you're having trouble accessing the links:
desktop (ignore the italics / since then we decided to italicize) 
<img width="368" alt="Screenshot 2023-05-17 at 9 44 50 AM" src="https://github.com/Princeton-CDH/lenape-timetree/assets/44615389/d23f53b3-cdb4-45c1-a6a3-413fd0feb60d">

mobile 
<img width="289" alt="Screenshot 2023-05-17 at 9 45 52 AM" src="https://github.com/Princeton-CDH/lenape-timetree/assets/44615389/e603d65a-bdc9-433c-8c2b-c81d8dfa5f19">


- [here is the link to the typography for dev page](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=960%3A4947&t=fT6fpPyIZUkfwCXZ-1) – I have moved it to the top of the Figma project file.

**Comment by rlskoeser** [comment]
completed in #205
