### ISSUE TITLE
Create styles and guidelines for image captions/citation/titles 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#193]

**Comment by gissoo** [comment]
@rlskoeser @jhimpele please review the styles I have proposed based on the examples Rebecca shared with me and read the notes I have included next to each. (the image used in the mock up is not accurate) 

- [for images without caption, with source ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1835%3A4953&t=vPBAuQVyxwf8m2JN-1)
- [for images with caption and source](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1835%3A5732&t=vPBAuQVyxwf8m2JN-1) 
- [for images with nothing but source](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1835%3A5732&t=vPBAuQVyxwf8m2JN-1)

NOTE: I was going to suggest to link the caption and/or title when possible but I think the caption with an underline will be hard to read that way if it's longer than two lines, therefore I have omitted that proposal.

**Comment by jhimpele** [comment]
Thanks for explaining. Just an odd title!
Jeff.


Jeffrey Himpele.
Director, VizE Lab for Ethnographic Data Visualization
Lecturer in Anthropology
319-320 Burr Hall | Princeton University

vizelab.princeton.edu<http://vizelab.princeton.edu/>


On 5/10/23, 11:54 AM, "gissoo" wrote:


@jhimpele<https://github.com/jhimpele> the names Lossing and Barritt are there in the database, it's the name of the work the source links to. I used the existing captions in the examples Rebecca shared. Here is the example with Lossing and Barritt. <https://lenape-timetree-dev.onrender.com/#fallen-timbers>

Sorry about the link for the one with only a source, I fixed it, you should be able to view that page now.

**Comment by gissoo** [comment]
> Gissoo, these look good. I like the smaller font, I think it will be more distinct than it was before.
> 
> Your suggestion for only applying a caption to the second of two images needs to be implemented on the content editing side (although I'll probably also need to adjust spacing for two figures in a row). Should we add some instructions about this to our contributor doc?
> 

Adding instructions to our contributor doc would be great! I think:
-  it should not repeat if the caption and the source are the same, they should be written 
- if only the caption is the same for both it should be written once ideally at the bottom of the last image
- if only the source is the same for both it should be written once ideally at the bottom of the last image 
> Are you proposing we add the "courtesy of" text when there is no caption but we have a source?
> 

- Yes, because when there is a link it's pretty obvious that it's the source – but without any captions it's a bit awkward – I don't feel strongly but I think it's not necessary to have "courtesy of" at all times

> It's possible to have a source without a source link. Is it fine if it's just italicized and not a link?
> 

- Yes, it is fine, it might be better to have "courtesy of" for such cases too. 

> Sorry about the weird Lossing and Barritt title, that might be one of the ones that I added when I implementing and testing the basic figure functionality. I can check the spreadsheet and see if it should be updated.

**Comment by gissoo** [comment]
- @rlskoeser @jhimpele [I added an example](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1894%3A2065&t=0EcqVY6lqxlhQWqJ-1) for when the source doesn't have a link 

- for the other recommendation I made for images that have at least one thing (caption/source) in common I can't find any examples right now in the database, but it can be documented in our contributor docs and addressed when/if such cases come up. 
It will be a smoother reading experience if any text for the images just come at the bottom of the last image in these cases.
