### ISSUE TITLE
As a mobile user, I want to see some leaf labels to be visible when the tree is not zoomed, so I more easily understand I can interact with the tree.

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#195]
Below is a list of leaves Jeff recommended:
Princeton Settlement, 
Walking Purchase,
Delaware Nation in Oklahoma, 
Pro-British Lunaapew, 
Witherspoon’s Reflections, 
Honorary Degree, 
Native Removal Act, 
Midwest Resettlement, 
Land Rights, 
American Indian Religious Freedom Act, 
Language Camp

**Comment by rlskoeser** [comment]
implemented in #228
