### ISSUE TITLE
As a user, I want the option of zooming in on the timetree on desktop and with buttons, so that the content and functionality is accessible in a variety of modes.

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#200]
- Add buttons and function to zoom in and out of the tree on desktop and mobile to address WCAG requirements  (can't rely on gesture/scroll wheel)
- Add zoom capability on desktop for accessibility (low vision)

In the following Figma links you can find the +/- button styles and states on mobile and desktop along with notes on interaction: 
- [Default view on mobile and desktop](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1878%3A3628&t=0EcqVY6lqxlhQWqJ-1), 
- [selected leaf on mobile](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1878%3A3295&t=0EcqVY6lqxlhQWqJ-1), 
- and [interaction with zoom buttons on desktop](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1811%3A3159&t=0EcqVY6lqxlhQWqJ-1)

**Comment by rlskoeser** [comment]
@gissoo question about the desktop zoom, which of these do you prefer?

When the tree is zoomed, allow leaves to display behind the info panel:
![Screenshot 2023-05-19 at 9 55 36 AM](https://github.com/Princeton-CDH/lenape-timetree/assets/691231/0a70cd71-79e7-4f00-9f86-dc9f67ac1841)

Cut the tree off at the edge of the container (overflow is hidden), no leaves behind the panel:
![Screenshot 2023-05-19 at 9 55 56 AM](https://github.com/Princeton-CDH/lenape-timetree/assets/691231/c897e8d9-11bc-4587-bb8f-acb72f917d63)

**Comment by gissoo** [comment]
Rebecca and I viewed option 1 in max zoom and it looks great! But we revised the height of the zoom and full screen buttons on desktop to match the height of the panel so they don't look out of place 
![Screenshot 2023-05-23 at 12 30 20 PM](https://github.com/Princeton-CDH/lenape-timetree/assets/44615389/32c6fad5-b415-4636-bb32-a861bbf73116)

**Comment by rlskoeser** [comment]
completed in #218
