### ISSUE TITLE
Trunk lines disconnected

### ISSUE THREAD

**Issue by jhimpele** [Princeton-CDH/lenape-timetree#232]
1. Tree looks like it is shifted to the left a little and disconnected the Dedication strings. 

2. The trunk itself is disconnected from roots if the browser window is too large (vertically).

<img width="209" alt="Screenshot 2023-06-08 at 2 55 51 PM" src="https://github.com/Princeton-CDH/lenape-timetree/assets/93936615/0cf2a71a-1e51-47fb-a9c7-7d6b3966b9c4">

**Comment by rlskoeser** [comment]
@jhimpele can you share the screen size / browser size?

**Comment by jhimpele** [comment]
This is a Mac Studio 27" screen. The first shot here is the full vertical extent of the screen, and the second reduces height so the trunk connects to the roots. Does the height resolution of these two images give you what you ask? 
<img width="1184" alt="Screenshot 2023-06-08 at 3 06 04 PM" src="https://github.com/Princeton-CDH/lenape-timetree/assets/93936615/70a53a10-a392-40a2-93fc-c8d184212143">
<img width="1185" alt="Screenshot 2023-06-08 at 3 06 40 PM" src="https://github.com/Princeton-CDH/lenape-timetree/assets/93936615/10e36728-54bd-4910-907f-aaab3dc6af5b">

**Comment by rlskoeser** [comment]
@gissoo would appreciate your advice on how to handle; could we set a max height on the page for desktop? (although then it will probably look weird at the bottom of the page...).

The point where the trunk lines go straight is actually the bottom of the svg proper. I extended them quite a bit to try to avoid this kind of disconnect, and could extend them even further (and add a bit more variation so they aren't as straight).

**Comment by jhimpele** [comment]
At full size it seems to be displaying correctly. The other issue now is that when I reduce the height of the screen past the bend in the trunk, it falls out of alignment. 
<img width="1036" alt="Screenshot 2023-06-12 at 10 10 08 AM" src="https://github.com/Princeton-CDH/lenape-timetree/assets/93936615/f02123d3-a384-4a6f-bbb4-3508da1b6997">

**Comment by gissoo** [comment]
@rlskoeser the resolution of Jeff's device seems to be 5120×2880 – maybe we should extend further, to what point are you extending them right now?

**Comment by rlskoeser** [comment]
@gissoo right now I'm extending them by 300 pixels within the svg; for context our svg viewbox is 800 pixels tall.  It's trivial for me to increase that 300 number if that would be a good enough solution for now.

**Comment by gissoo** [comment]
@rlskoeser thanks, yes, let's increase please

**Comment by rlskoeser** [comment]
addressed in #6cda2b7 back in June
