### ISSUE TITLE
disabled leaves & labels are not sufficiently visually disabled

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/lenape-timetree#264]
accessibility review feedback from @itmaybejj:

> Disabled items are not very disabled visually. E.g., at right, which items are clickable? It is hard to tell -- the color change from Ramapough to its surrounding leaves is < 3:1, but then it's not clear whether the next leaves over are in an active or disabled state.

suggestion:
> Maybe modify the text as well? Gray out disabled items?

## testing notes
- [x] confirm that labels for deselected are visually disabled/dimmed

1. select a leaf
2. select a tag on that leaf (may need to scroll down on the leaf detail panel)
3. confirm that labels for leaves without that tag are dimmed (lower opacity, no text shadow)

**Comment by rlskoeser** [comment]
looks to me that this is a bug as well as an :accessibility: fix, since there is a css selector for deselected labels; it's just that the styles weren't being applied the way we needed them to be

**Comment by mnaydan** [comment]
This looks fixed as well - when a leaf tag is selected, the disabled leaves no longer have the text shadow and do appear lower opacity. It looks really nice and clear.
