### ISSUE TITLE
disabled leaves are clickable when the tree is zoomed in

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/lenape-timetree#265]
bug reported as part of accessibility review feedback from @itmaybejj (related to #264):

> It gets a bit more confusing as which leaves are clickable changes based on zoom level. Zoomed out, only the active filtered items are clickable. Zoomed in, all items are.

## testing notes
- [x] confirm that leaves are properly disabled when the tree is zoomed

1. select a leaf
2. select a tag on that leaf (may need to scroll down within the leaf detail panel)
3. confirm that leaves without the selected tag can't be interacted with (no click, no hover effect)
4. use the + button to zoom in
5. confirm that leaves without the tag are still not interactive

**Comment by mnaydan** [comment]
I followed the indicated steps and can confirm that that the leaves are properly disabled when the tree is zoomed in (I tested at all levels of zoom).
