### ISSUE TITLE
Implement colors for the site 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#42]
[Here are the colors with labels](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=414%3A71&t=bm7LfsUUocpVMcUt-1) – please let me know if you have any questions. 

there is a chance the "branch region background" color may change.

**Comment by rlskoeser** [comment]
completed in PR #45, which has been reviewed and merged
