### ISSUE TITLE
Implement desktop and mobile type styles based on the design specifications 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#47]
[Here are the design specs in the type table on figma ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=484%3A67&t=CJH26KrwLUoQzVxD-1)

Not in scope: the site title type style

**Comment by rlskoeser** [comment]
implemented and reviewed in PR #50
