### ISSUE TITLE
As a user I want to close an open panel when I do not need the content so that it doesn’t clutter the screen and/or obscure my view of the tree on mobile and if I want to view the intro again on desktop. 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#56]
What's in scope: 
- the sequence and logic of the panel (how a panel can be closed/collapsed + how the project intro can be viewed)
- the visual style of the two buttons (button to bring back the project intro, and the one to collapse the panel)

**Comment by gissoo** [comment]
@rlskoeser @jhimpele Please review the logic I've proposed [here on figma](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=674%3A5799&t=aynnaO3skFFdyoKD-1) on the sequence and logic of interactions with the leaf info and the project intro panels on desktop and mobile. I have numbered the sequence and included descriptions next to each. 

One question for you: do you think it's intuitive that the user will have to close a leaf panel to view the project intro again on desktop? Is this logic intuitive? I think we'd discussed this before and seems to be simple and fine, but want to make sure I bring up the intuitiveness of it as we're deciding. 

- Note: I'm also proposing that when the project intro is displayed the “i” icon is disabled at the top – 30% opacity), once a leaf info is displayed the “i” is abled again to let the user select it to view the project intro again

**Comment by rlskoeser** [comment]
@gissoo everything makes sense here and matches how I was thinking about it. The icons and spacing look good. 

I'm not sure how obvious it is that closing a leaf panel will show the intro on desktop — but I'm not sure how much it is _needed_ to show the intro after the beginning, and I think users will find it. (They could also reload the page to see it, fwiw.)

I wonder if it will be confusing that the info icon is disabled when the page is first loaded on mobile, but I think that it will probably be clear enough in actual use.

**Comment by jhimpele** [comment]
My two cents: I don't think it needs to be obvious that closing a leaf panel will return to the intro panel. Mainly because I'm not sure viewers will want to do that. On the other hand, this behavior will be obvious in actual use once the first time a user closes the panel. For that reason, I don't think the ext "I" icon is needed. 

Also, where is the Home root leading too?

**Comment by gissoo** [comment]
@jhimpele I think the home root/footer button should behave the same way as refreshing the homepage/tree page. (We can call this page anything that makes sense to us) 

@rlskoeser @jhimpele thank you for the comments! they're super helpful. @rlskoeser I think the disabled button will make sense in actual use as you said. 

@jhimpele , the "i" is only on mobile since there is no way back to the intro unless the user refreshes the page/clicks on the home button in the footer. I think UX-wise it's better to account for it than not, I understand it may not seem crucial but it's better practice to account for ways to undo something that's done, or vice versa on the interface other than relying on refreshing the page.

**Comment by gissoo** [comment]
This issue seems to be resolved. I have adjusted the "i" icon so it's 24px, it seemed to be too large.

**Comment by rlskoeser** [comment]
Thanks @gissoo. Do we have an implementation issue or need to create one?
