### ISSUE TITLE
As the project team we want the site title/project title to be displayed with a distinct font to display so that it stands out to the users and becomes memorable

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#59]

**Comment by gissoo** [comment]
@rlskoeser @jhimpele please take a look at [these display fonts on Figma to use for the site title ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1182%3A1053&t=XMrNuENzsEaPE8VH-1)

NOTE: 
- only 3 of them were available to try on the mockups, the rest I just took screenshots with the word "Lunaapahkiing" to get a sense of what they would look like. 

- I have placed a <3 next to two of them, I liked those more, let me know if you have favorites.

**Comment by jhimpele** [comment]
Lots of really nice choices here @gissoo.  I don't see the <3. Which do you and @rlskoeser like?

**Comment by jhimpele** [comment]
oh wait, it is a heart.....

**Comment by rlskoeser** [comment]
My favorite is Montecatini Pro. I also like Macondo, although the E in Macondo bothers me for some reason.

Others I like: Intro Cond, Linotype Spitz Book

I don't like the Wood Font Two. I'm not sure about the other "woodsy" fonts either... maybe Woodtype Collection Roast.

**Comment by jhimpele** [comment]
So that we have the lists in one place, I did like Woodtype Roast, Posterama semibold, Bourton Hand Base, Woodout, and   Recordi Greto. So far only Woodtype and Macondo are in common among different pairs of us. I agree about the macondo E and Macondo still looks like an Asian inflected style to me. And the Montecatini could work as a title, since it is a one time use. I wonder if it's difficult to read....

**Comment by gissoo** [comment]
We have decided to:
- go with Montecatini Normale Pro 
- use more than one weight and size to emphasize on Lenapehakking and make the site title more readable 

@rlskoeser @jhimpele just double checking before I make the purchase, [please take a look here on their site](https://www.myfonts.com/collections/montecatini-pro-font-louise-fili?gclid=Cj0KCQjw8qmhBhClARIsANAtbocLz9M7Nao6lafZViwMrpwZ0pbRdZtNJe6VvH8aAY5YX05RMWCrWAMaAhvoEALw_wcB) – I showed you the three weights from the normale family (if you scroll down you'll see the normale family separately, (also screenshot below) – can we buy the light and bold? Or are there other weights you prefer? 
<img width="907" alt="Screenshot 2023-04-04 at 10 23 04 AM" src="https://user-images.githubusercontent.com/44615389/229823260-a7816cd2-c730-4ccf-a011-b762423ef85c.png">

**Comment by gissoo** [comment]
@jhimpele thanks for reminding me! Here is what it would look like

![Screenshot 2023-04-04 at 12 11 10 PM](https://user-images.githubusercontent.com/44615389/229852896-af39cde0-afac-4279-96b0-88b78dae1228.png)

**Comment by gissoo** [comment]
@jhimpele thanks for reminding me, here is what it would look like
![Screenshot 2023-04-04 at 12 12 20 PM](https://user-images.githubusercontent.com/44615389/229853184-ec60424e-9e88-463a-80ac-36525b5855ee.png)

**Comment by jhimpele** [comment]
THanks @gissoo. I'm fine with your suggestion of Normale and Normale Bold. @rlskoeser what do you think?

**Comment by rlskoeser** [comment]
@jhimpele I prefer light and semibold — the bold seems too thick and I think the semibold is enough contrast. But happy to  to Gissoo's judgement, as you said!

**Comment by jhimpele** [comment]
Yes they work too. @gissoo can you take a look at these 4 on the site? That might be the best way for you to get a feel for the weights. Your call!

**Comment by gissoo** [comment]
@rlskoeser @jhimpele thank you! Yes, Rebecca and I agreed on the light and semi-bold versions but then the price difference was very little so we agreed to buy the normale pack. I also went ahead and purchased it for 2 users and made Rebecca the main licensee, better for use cases for the future. (thinking of the potential use of this font for making Lenape swags for whenever the public launch is happening since my term is ending in June). 

- [Please look at this](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1182%3A1317&t=FSaqKRHIk4L15NMU-1) and let me know what you think! I tried it with semibold but didn't like it much, I also tried putting the "Princeton Timetree" in two lines but also didn't like it. Let me know if you have thoughts.

**Comment by rlskoeser** [comment]
@gissoo I agree with Jeff that Lunaapahkiing and Princeton need to be given equal weight here. I leave it up to you as to how you convey that visually, but it's important that they should be seen as on the same level or equivalent somehow.

**Comment by gissoo** [comment]
@rlskoeser @jhimpele thank you! I wasn't on the same page. [How about this?](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1297%3A953&t=903OSphjvODnC7jg-1)

**Comment by gissoo** [comment]
to document our slack discussions here, Keely reviewed and liked the first version better, and added "I'm still not sure if Princeton and Timetree being analogous is necessarily a problem. The way I see it, the project originally flowed from the idea of an alternative Princeton Timeline. What makes this project different is that it recenters Princeton history by focusing on the land and Lenape people. Therefore, having Lunaapahkiing look different from the rest of the words highlights why this project is different from what has been done before. (And it highlights Munsee language use.) There could be more to it that I am not considering, so I am happy to hear your thoughts" 

Jeff and Rebecca agreed, and this also matches how I was thinking about it initially and am totally on the same page with Keely on this, glad she reviewed it and articulated it so well.

**Comment by gissoo** [comment]
I have uploaded the site titles as SVGs for mobile and desktop to github, themes > static > img > icon
