### ISSUE TITLE
As a user I want to read the other pages on the site so that I can learn more about project 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#64]
In scope:

- grid on desktop (i.e. width of the content on the page)
- H1 and H2 styles and spacing
- paragraph styles
- bullet styles
- image and image caption styles
- link styles 
- resources/citation styles (indents, italics, links, spacing)
- list styles (spacing and header styles)
- spacing between elements 

NOTE: I am not creating a single page design for each root page, instead I'm proposing all the styles on one page and showing how they would apply to our content (taken from the root data docs on the drive).

**Comment by gissoo** [comment]
@jhimpele @rlskoeser please read above to see what is in scope for this issue – review [the content styles I've proposed for mobile and desktop on Figma ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1046%3A4515&t=WfUVCcrtNoS3ym1v-1) – and let me know if there are styles that I've missed. 
I tried to look at our docs and see what kinds of content we'll have on our root pages.

**Comment by jhimpele** [comment]
@gissoo This looks good as a template for these pages. You may need to create a style for the bibliography and list of links. Not sure.

**Comment by gissoo** [comment]
@rlskoeser @jhimpele thanks for writing – we decided at the meeting that what is needed for bibliography and link styles are currently there in the designs.

@rlskoeser if we make H1 bigger it will be applied to the leaf titles as well, is that ok?

**Comment by rlskoeser** [comment]
@gissoo would it be better to adjust the H2s? I defer to you about the H1 on leaf titles — I think the panel looks good as it is, but I trust you if you think it's ok to go a bit larger.

**Comment by gissoo** [comment]
@rlskoeser that was my first instinct, but the problem with adjusting the h2 is that its size would become the same as the body text
