### ISSUE TITLE
As a user on a smaller screen, I want to zoom in on the timetree so that I can view and interact with the content more easily.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/lenape-timetree#69]
depends on #35 

comprises the following functionality / user stories:
- No zoom on desktop
- Zoom on mobile
- Automatically zoom when a leaf is clicked
- option/button to reset zoom
- automatically zoom out when a tag is selected (default zoom level for now)
- ideally, if tag is closed but leaf is not, automatically zoom back to the selected leaf

## dev notes
- [x] hide labels on mobile at default zoom level, show once zoomed
- [x] limit zoom scale extent 1-4
- [x] constrain zooming so that the left and right edges of the svg don't move from the edge of the screen when zooming in near the edge
- [x] when a leaf is selected at any zoom level, automatically zoom to zoom level 4 and center on the selected leaf (possibly higher than center to make sure it is clear of the panel)
- [x] when the panel closes, do not change the zoom level
- [x] disable zoom on desktop; handle resize gracefully
- [x] set different svg width for mobile and desktop; handle resize gracefully
- [x] implement zoom reset button; not visible/interactive until zoomed
- tag + zoom interactions
  - [x] when you select a tag, zoom out so you can see all tagged leaves (ideally just the tagged ones, but ok to zoom all the way out)
  - [x] if you close the tag but not the leaf, zoom back in on the selected leaf

## revisions after PR review
- [x] update code from latest development version
- [x] difficulty selecting leaves (debug layer order/overlap)
- [x] adjust century spacing/alignment (esp. how much space centuries are taking up horizontally) 
- [x] century label styling
- [x] century label sizing on zoom; can we scale the same as labels?
- [x] figure out what to do about designed background color for century labels

**Comment by rlskoeser** [comment]
notes from today's working session:

- on mobile, don't show leaf labels at default zoom level, but can show them at next zoom level
- limit zoom scale extent 1-4
- constrain zooming so that the left and right edges of the svg don't move from the edge of the screen when zooming in near the edge
- when a leaf is clicked at any zoom level, automatically zoom to zoom level 4 and center on the selected leaf (possibly higher than center to make sure it is clear of the panel)
- when the panel closes, do not change the zoom level

**Comment by rlskoeser** [comment]
@gissoo I need your advice (or maybe a co-working session) on the century label sizing. The font is styled at 14px size as you designed, but the svg is 800 width on mobile, so they're being displayed at somewhere about half size (depends on the width of the screen on the mobile device). They're the same size as the leaf labels we're not showing when the tree is zoomed out, but obviously that solution doesn't work for the centuries.

I will experiment some with transforming the century labels on zoom so I know more about our options for resizing.

**Comment by gissoo** [comment]
@rlskoeser can we make the century label 16px on mobile as well? thanks for letting me know

**Comment by rlskoeser** [comment]
increasing estimate to 5pts since we didn't break out any separate user stories for related zoom functionality

**Comment by rlskoeser** [comment]
@gissoo question about zoom behavior: should anything change when you show or hide the intro panel with the info button? It's currently reseting zoom when you close or open the panel, but I don't remember why and I don't see it on our list.

**Comment by rlskoeser** [comment]
implemented in #142
