### ISSUE TITLE
As a mobile user, I want a way to get back to the project introduction after I've closed it, so I can refer back to it after exploring the timetree.

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#85]
implement the information icon on mobile to display the introduction panel 

logic of the functionality, along with the placement and dimensions of the icon are on [this figma page and can be inspected here](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=674%3A5799&t=yeSCvclFJyJHvPoe-1)

The icon is taken from phosphor icons

## dev notes
- add a button with info icon to mobile header (icon asset & style added in #130)
- button should be disabled when the intro is showing
- if panel is showing leaf details or is closed, button is enabled
- clicking/tapping the button will show the panel with the introduction content

Note: it may be worth refactoring panel-centric code into an object/component; may make it possible to get ride of some code duplication and also make it more readable (e.g. `Panel.close()`)

## revisions
- [x] info button enabled whenever intro panel is not visible (even if leaf details are visible)
- [x] info button should show intro when clicked (either closed or leaf details visible)
- [x] when the page is loaded with a tag but no leaf selected (i.e., coming from the tag index), the intro should not be displayed on mobile
- [x] collapsing the info panel should not deselect the current tag

**Comment by rlskoeser** [comment]
upgrading from 1pt to 2 to account for the different states that need to be handled

**Comment by rlskoeser** [comment]
increasing to 3 pts due to the complexity of the different interactions between panel, selected leaf, selected tag, etc.

**Comment by rlskoeser** [comment]
reviewed on #149; acceptance testing on PR #158
