### ISSUE TITLE
Update the color of the panel to match the designs 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#86]
[Here is the design on Figma ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=996%3A1639&t=YOswE7ELILV9sIqC-1)

**Comment by rlskoeser** [comment]
@gissoo is this Figma link still correct, or should I be using the "color for dev - March 27" page? 

Also, question about text color: when I inspect the panel on that page the text color is `#F8F8F8` but the documented color on the left still shows `#FEFEFE`  — which one is correct?

**Comment by gissoo** [comment]
@rlskoeser thank you, sorry, it must have not copied properly. It should have the correct link now. Yes, that is the right page. 
@rlskoeser please use #FEFEFE – follow the color library. I need to fix that inconsistency.

**Comment by rlskoeser** [comment]
Thank you for responding, @gissoo.

This task is really a subset of #125, so I'm going to mark it as a duplicate.
