### ISSUE TITLE
Implement leaf states and additional colors for them 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#92]
[Here is the corresponding design issue ](https://github.com/Princeton-CDH/lenape-timetree/issues/89)
[The styles are here on Figma](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=925%3A10516&t=h5eU2Vi3uzpGcOEW-1)

**Comment by rlskoeser** [comment]
initial implementation in #98
